//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMove_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedData
    {
        public int Id { get; set; }
        public int postcode { get; set; }
        public int snelheid { get; set; }
        public string tech { get; set; }
        public string centrale { get; set; }
        public System.DateTime datum { get; set; }
        public int bevolkingsdichtheid { get; set; }
    }
}
