//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMove
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeedApplicationDBEntities : DbContext
    {
        public SpeedApplicationDBEntities()
            : base("name=SpeedApplicationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SpeedData> SpeedData { get; set; }
        public virtual DbSet<SpeedLocations> SpeedLocations { get; set; }
        public virtual DbSet<WifiData> WifiData { get; set; }
    }
}
