//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMove
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedLocations
    {
        public int Id { get; set; }
        public Nullable<double> nelat { get; set; }
        public Nullable<double> nelng { get; set; }
        public Nullable<double> swlat { get; set; }
        public Nullable<double> swlng { get; set; }
        public Nullable<double> cnlat { get; set; }
        public Nullable<double> cnlng { get; set; }
        public int postcode { get; set; }
    }
}
