//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourMove
{
    using System;
    using System.Collections.Generic;
    
    public partial class WifiData
    {
        public int Id { get; set; }
        public string postcode { get; set; }
        public int huisnummer { get; set; }
        public string spotnaam { get; set; }
        public string aanbieder { get; set; }
    }
}
